apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: piezo-ingress
spec:
  rules:
    - host: stank8smaster
      http:
        paths:
          - backend:
              serviceName: piezo-app-service
              servicePort: web
            path: /piezo/
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: prometheus-ingress
spec:
  rules:
    - host: stank8smaster
      http:
        paths:
          - backend:
              serviceName: piezo-monitor-prometheus-o-prometheus
              servicePort: web
            path: /prometheus/
---
kind: Service
apiVersion: v1
metadata:
  name: spark-pods-service
  namespace: default
  labels:
    spark-role: monitor
spec:
  selector:
    version: 2.4.0
  ports:
  - name: web
    port: 8090  # Default metrics port for prometheus (DO NOT CHANGE)
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-pods-service-monitor
  labels:
    release: piezo-monitor # What is matched by the prometheus crd def (kubectl get prometheus -o yaml --all-namespaces)
spec:
  endpoints:
  - port: web
  selector:
    spark-role: monitor
---
kind: Service
apiVersion: v1
metadata:
  name: spark-operator-service
  namespace: spark-operator
  labels:
    spark-role: monitor
spec:
  selector:
    app.kubernetes.io/name: sparkoperator
  ports:
  - name: web
    port: 10254  # Default metrics port for spark operator (DO NOT CHANGE)
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-operator-service-monitor
  labels:
    release: piezo-monitor # What is matched by the prometheus crd def (kubectl get prometheus -o yaml --all-namespaces)
spec:
  endpoints:
  - port: web
  namespaceSelector:
    matchNames:
    - spark-operator
  selector:
    spark-role: monitor
